services:
  fraud-api:
    build:
      context: ./apps/fraud-api
    image: finguard/fraud-api:local
    environment:
      FRAUD_REVIEW_THRESHOLD: "45"
      FRAUD_BLOCK_THRESHOLD: "75"
      RECENT_TRANSACTION_LIMIT: "40"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 3s
      retries: 5

  dashboard:
    build:
      context: ./apps/dashboard
    image: finguard/dashboard:local
    depends_on:
      fraud-api:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/nginx-health"]
      interval: 10s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.55.1
    profiles: ["observability"]
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=2d"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - fraud-api

  grafana:
    image: grafana/grafana:11.3.0
    profiles: ["observability"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  vault:
    image: hashicorp/vault:1.18
    profiles: ["security"]
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: finguard-root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    command: ["vault", "server", "-dev"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    profiles: ["logging"]
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    profiles: ["logging"]
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
