apiVersion: batch/v1
kind: Job
metadata:
  name: seed-finguard-secret
  namespace: vault
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed-secret
          image: hashicorp/vault:1.18
          env:
            - name: VAULT_ADDR
              value: http://vault:8200
            - name: VAULT_TOKEN
              value: finguard-root
          command:
            - /bin/sh
            - -c
            - |
              sleep 10
              vault kv put secret/finguard \
                FRAUD_REVIEW_THRESHOLD=45 \
                FRAUD_BLOCK_THRESHOLD=75 \
                FINGUARD_API_TOKEN=""
