apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.18
          args: ["vault", "server", "-dev"]
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: finguard-root
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: 0.0.0.0:8200
          ports:
            - name: http
              containerPort: 8200
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: http
            initialDelaySeconds: 8
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
spec:
  selector:
    app.kubernetes.io/name: vault
  ports:
    - name: http
      port: 8200
      targetPort: http
